name: QiitaMobile
configs:
  Debug: debug
  Release: release
settings:
  base:
    ALWAYS_SEARCH_USER_PATHS: "NO"
    CLANG_ANALYZER_NONNULL: "YES"
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: "YES_AGGRESSIVE"
    CLANG_CXX_LANGUAGE_STANDARD: "gnu++14"
    CLANG_CXX_LIBRARY: "libc++"
    CLANG_ENABLE_MODULES: "YES"
    CLANG_ENABLE_OBJC_ARC: "YES"
    CLANG_ENABLE_OBJC_WEAK: "YES"
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: "YES"
    CLANG_WARN_BOOL_CONVERSION: "YES"
    CLANG_WARN_COMMA: "YES"
    CLANG_WARN_CONSTANT_CONVERSION: "YES"
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: "YES"
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: "YES_ERROR"
    CLANG_WARN_DOCUMENTATION_COMMENTS: "YES"
    CLANG_WARN_EMPTY_BODY: "YES"
    CLANG_WARN_ENUM_CONVERSION: "YES"
    CLANG_WARN_INFINITE_RECURSION: "YES"
    CLANG_WARN_INT_CONVERSION: "YES"
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: "YES"
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: "YES"
    CLANG_WARN_OBJC_LITERAL_CONVERSION: "YES"
    CLANG_WARN_OBJC_ROOT_CLASS: "YES_ERROR"
    CLANG_WARN_RANGE_LOOP_ANALYSIS: "YES"
    CLANG_WARN_STRICT_PROTOTYPES: "YES"
    CLANG_WARN_SUSPICIOUS_MOVE: "YES"
    CLANG_WARN_UNGUARDED_AVAILABILITY: "YES_AGGRESSIVE"
    CLANG_WARN_UNREACHABLE_CODE: "YES"
    CLANG_WARN__DUPLICATE_METHOD_MATCH: "YES"
    CODE_SIGN_IDENTITY: "iPhone Developer"
    COPY_PHASE_STRIP: "NO"
    ENABLE_STRICT_OBJC_MSGSEND: "YES"
    GCC_C_LANGUAGE_STANDARD: "gnu11"
    GCC_NO_COMMON_BLOCKS: "YES"
    GCC_WARN_64_TO_32_BIT_CONVERSION: "YES"
    GCC_WARN_ABOUT_RETURN_TYPE: "YES_ERROR"
    GCC_WARN_UNDECLARED_SELECTOR: "YES"
    GCC_WARN_UNINITIALIZED_AUTOS: "YES_AGGRESSIVE"
    GCC_WARN_UNUSED_FUNCTION: "YES"
    GCC_WARN_UNUSED_VARIABLE: "YES"
    IPHONEOS_DEPLOYMENT_TARGET: "13.0"
    MTL_FAST_MATH: "YES"
    SDKROOT: "iphoneos"
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: "dwarf"
      ENABLE_TESTABILITY: "YES"
      GCC_DYNAMIC_NO_PIC: "NO"
      GCC_OPTIMIZATION_LEVEL: "0"
      GCC_PREPROCESSOR_DEFINITIONS:
        - "DEBUG=1"
        - "$(inherited)"
      MTL_ENABLE_DEBUG_INFO: "INCLUDE_SOURCE"
      ONLY_ACTIVE_ARCH: "YES"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      MTL_ENABLE_DEBUG_INFO: "NO"
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      ENABLE_NS_ASSERTIONS: "NO"
      SWIFT_COMPILATION_MODE: "wholemodule"
      VALIDATE_PRODUCT: "YES"
targets:
  QiitaMobile:
    type: application
    platform: iOS
    sources: QiitaMobile
    preBuildScripts:
      - script: |
          "${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" "$SRCROOT"
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        CODE_SIGN_STYLE: "Automatic"
        INFOPLIST_FILE: "QiitaMobile/Info.plist"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
        PRODUCT_BUNDLE_IDENTIFIER: "tsukadayyy.QiitaMobile"
        PRODUCT_NAME: "$(TARGET_NAME)"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
      configs:
        Debug:
        Release:
  QiitaMobileTests:
    type: bundle.unit-test
    platform: iOS
    sources: QiitaMobileTests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
        BUNDLE_LOADER: "$(TEST_HOST)"
        CODE_SIGN_STYLE: "Automatic"
        INFOPLIST_FILE: "QiitaMobileTests/Info.plist"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"
        PRODUCT_BUNDLE_IDENTIFIER: "tsukadayyy.QiitaMobileTests"
        PRODUCT_NAME: "$(TARGET_NAME)"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/QiitaMobile.app/QiitaMobile"
      configs:
        Debug:
        Release:
  QiitaMobileUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: QiitaMobileUITests
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
        CODE_SIGN_STYLE: "Automatic"
        INFOPLIST_FILE: "QiitaMobileUITests/Info.plist"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"
        PRODUCT_BUNDLE_IDENTIFIER: "tsukadayyy.QiitaMobileUITests"
        PRODUCT_NAME: "$(TARGET_NAME)"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        TEST_TARGET_NAME: "QiitaMobile"
      configs:
        Debug:
        Release: